# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.destroy_all
demo_user = User.create({username: "demoUser", email: "demo@example.com", password: "demopassword"})

StudySet.destroy_all
study_set1 = StudySet.create({title: "Alphabet" , user_id: demo_user.id})
study_set2 = StudySet.create({title: "Basketball" , user_id: demo_user.id})
study_set3 = StudySet.create({title: "Programming" , user_id: demo_user.id})
study_set4 = StudySet.create({title: "Sports", user_id: demo_user.id})
study_set5 = StudySet.create({title: "Games", user_id: demo_user.id})
study_set6 = StudySet.create({title: "React/Redux", user_id: demo_user.id})
study_set7 = StudySet.create({title: "Rails", user_id: demo_user.id})
study_set8 = StudySet.create({title: "Football", user_id: demo_user.id})
study_set9 = StudySet.create({title: "Harry Potter spells", user_id: demo_user.id})
study_set10 = StudySet.create({title: "Disney", user_id: demo_user.id})
study_set11 = StudySet.create({title: "Candy", user_id: demo_user.id})
study_set12 = StudySet.create({title: "Coffee", user_id: demo_user.id})
study_set13 = StudySet.create({title: "March Madness", user_id: demo_user.id})


Folder.destroy_all
folder1 = Folder.create({name: "Programming Flashcards", description: "Study sets relating to programming", user_id: demo_user.id})
folder2 = Folder.create({name: "Sports Flashcards", description: "Study sets relating to sports", user_id: demo_user.id})
folder3 = Folder.create({name: "Fictional World", description: "Study sets relating to fictional worlds and characters", user_id: demo_user.id})
folder4 = Folder.create({name: "Miscellaneous Folder", description: "Miscellaneous study sets", user_id: demo_user.id})

StudySetFolder.destroy_all
study_set_folder1 = StudySetFolder.create({folder_id: folder1.id, study_set_id: study_set3.id})
study_set_folder2 = StudySetFolder.create({folder_id: folder1.id, study_set_id: study_set6.id})
study_set_folder3 = StudySetFolder.create({folder_id: folder1.id, study_set_id: study_set7.id})
study_set_folder4 = StudySetFolder.create({folder_id: folder2.id, study_set_id: study_set2.id})
study_set_folder5 = StudySetFolder.create({folder_id: folder2.id, study_set_id: study_set4.id})
study_set_folder6 = StudySetFolder.create({folder_id: folder2.id, study_set_id: study_set13.id})
study_set_folder7 = StudySetFolder.create({folder_id: folder3.id, study_set_id: study_set9.id})
study_set_folder6 = StudySetFolder.create({folder_id: folder3.id, study_set_id: study_set10.id})
study_set_folder6 = StudySetFolder.create({folder_id: folder4.id, study_set_id: study_set5.id})
study_set_folder6 = StudySetFolder.create({folder_id: folder4.id, study_set_id: study_set11.id})
study_set_folder6 = StudySetFolder.create({folder_id: folder4.id, study_set_id: study_set12.id})

Card.destroy_all
Card.create({term: "A", definition: "apple", study_set_id: study_set1.id})
Card.create({term: "B", definition: "basketball", study_set_id: study_set1.id})
Card.create({term: "C", definition: "cat", study_set_id: study_set1.id})
Card.create({term: "D", definition: "dog", study_set_id: study_set1.id})
Card.create({term: "E", definition: "elephant", study_set_id: study_set1.id})
Card.create({term: "F", definition: "fan", study_set_id: study_set1.id})
Card.create({term: "G", definition: "goat", study_set_id: study_set1.id})
Card.create({term: "H", definition: "hat", study_set_id: study_set1.id})
Card.create({term: "I", definition: "insect", study_set_id: study_set1.id})
Card.create({term: "J", definition: "jack", study_set_id: study_set1.id})
Card.create({term: "K", definition: "kangaroo", study_set_id: study_set1.id})
Card.create({term: "L", definition: "lion", study_set_id: study_set1.id})
Card.create({term: "M", definition: "monkey", study_set_id: study_set1.id})
Card.create({term: "N", definition: "newspaper", study_set_id: study_set1.id})
Card.create({term: "O", definition: "orange", study_set_id: study_set1.id})
Card.create({term: "P", definition: "pen", study_set_id: study_set1.id})
Card.create({term: "Q", definition: "quilt", study_set_id: study_set1.id})
Card.create({term: "R", definition: "raccoon", study_set_id: study_set1.id})
Card.create({term: "S", definition: "shark", study_set_id: study_set1.id})
Card.create({term: "T", definition: "tree", study_set_id: study_set1.id})
Card.create({term: "U", definition: "underwear", study_set_id: study_set1.id})
Card.create({term: "V", definition: "vacuumn", study_set_id: study_set1.id})
Card.create({term: "W", definition: "washing machine", study_set_id: study_set1.id})
Card.create({term: "X", definition: "xylophone", study_set_id: study_set1.id})
Card.create({term: "Y", definition: "yak", study_set_id: study_set1.id})
Card.create({term: "Z", definition: "zipper", study_set_id: study_set1.id})

Card.create({term: "Steph Curry", definition: "Three point king" , study_set_id: study_set2.id})
Card.create({term: "Lebron James", definition: "King", study_set_id: study_set2.id})
Card.create({term: "Shaq", definition: "Broken backboard", study_set_id: study_set2.id})
Card.create({term: "Draymond Green", definition: "Beast", study_set_id: study_set2.id})
Card.create({term: "Michael Jordan", definition: "GOAT", study_set_id: study_set2.id})
Card.create({term: "Vince Carter", definition: "Vinsanity", study_set_id: study_set2.id})
Card.create({term: "Derrick Rose", definition: "Always injured", study_set_id: study_set2.id})
Card.create({term: "Blake Griffin", definition: "Clipper frontcourt", study_set_id: study_set2.id})
Card.create({term: "Warriors", definition: "NBA Champs", study_set_id: study_set2.id})
Card.create({term: "Kobe Bryant", definition: "Lakers MVP", study_set_id: study_set2.id})

Card.create({term: "Programming", definition: "The art of creating a program", study_set_id: study_set3.id})
Card.create({term: "Loop", definition: "To do an action over and over", study_set_id: study_set3.id})
Card.create({term: "Decompose", definition: "To break down to smaller pieces", study_set_id: study_set3.id})
Card.create({term: "Debugging", definition: "Finding and fixing errors in programs", study_set_id: study_set3.id})
Card.create({term: "Code", definition: "1 or more commands/algorithm", study_set_id: study_set3.id})
Card.create({term: "Bug", definition: "An error in a program", study_set_id: study_set3.id})
Card.create({term: "Algorithm", definition: "A list of steps to finish a task", study_set_id: study_set3.id})
Card.create({term: "Abstraction", definition: "Pulling out specific differences to make one solution work for multiple problems", study_set_id: study_set3.id})
Card.create({term: "Function", definition: "A piece of code that you can easily call over and over again.", study_set_id: study_set3.id})

Card.create({term: "Tennis", definition: "Raquet, Ball, Tennis shoes, Shorts, T-shirt",study_set_id: study_set4.id})
Card.create({term: "Swimming", definition: "Swimsuit, Googles, Swimming pool",study_set_id: study_set4.id})
Card.create({term: "Gymnastics", definition: "Tracksuit, Headband, Overall",study_set_id: study_set4.id})
Card.create({term: "Baseball", definition: "Bat, Ball, Helmet, Uniform, Team, Kneepads",study_set_id: study_set4.id})
Card.create({term: "Karate", definition: "Mat, Belt, Uniform",study_set_id: study_set4.id})
Card.create({term: "Roller skating", definition: "Roller skates, Helmet",study_set_id: study_set4.id})
Card.create({term: "Soccer", definition: "Ball, Tennis shoes, Gloves, T-shirt, Shorts, Socks",study_set_id: study_set4.id})
Card.create({term: "Basketball", definition: "Ball, jersey",study_set_id: study_set4.id})

Card.create({term: "Flappy bird", definition: "RAGE", study_set_id: study_set5.id})
Card.create({term: "Madden 14", definition: "touchdown!", study_set_id: study_set5.id})
Card.create({term: "NBA 2K13", definition: "ballin''", study_set_id: study_set5.id})
Card.create({term: "Call of Duty Ghosts", definition: "360 NO SCOPE!", study_set_id: study_set5.id})
Card.create({term: "Minecraft", definition: "blocks only!", study_set_id: study_set5.id})
Card.create({term: "Monopoly", definition: "all about the money", study_set_id: study_set5.id})
Card.create({term: "Crossy Road", definition: "YES, new high score!", study_set_id: study_set5.id})

Card.create({term: "component", definition: "in react, the view part of mvc is represented in a ___", study_set_id: study_set6.id})
Card.create({term: "props", definition: "The component has an immutable property bag called ____", study_set_id: study_set6.id})
Card.create({term: "state", definition: "What is the property name of the component's user driven state of the UI?", study_set_id: study_set6.id})
Card.create({term: "render", definition: "Each component provides an implementation of the ___ method which creates the intermediate dom.", study_set_id: study_set6.id})
Card.create({term: "intermediate", definition: "The ____ DOM is converted into the real HTML DOM.", study_set_id: study_set6.id})
Card.create({term: "JSX", definition: "___ is an XML based extension to javascript which builds the component tree as a set of xml nodes", study_set_id: study_set6.id})
Card.create({term: "one", definition: "in react, data flow is ___ way", study_set_id: study_set6.id})
Card.create({term: "Flux", definition: "	
In the ____ pattern, the Store is the central authority for all data; any mutations to the data must occur within the store", study_set_id: study_set6.id})

Card.create({term: "app", definition: "where Models, Views and Controllers are. It's where most of Rails code goes", study_set_id: study_set7.id})
Card.create({term: "config", definition: "where the routes are, which handle requests from the browser", study_set_id: study_set7.id})
Card.create({term: "db", definition: "database and migration files", study_set_id: study_set7.id})
Card.create({term: "Gemfile", definition: "where gem files are. Gems add special features to a Rails app", study_set_id: study_set7.id})
Card.create({term: "ERB", definition: "Embedded Ruby-a way to insert Ruby code/objects in an HTML page", study_set_id: study_set7.id})
Card.create({term: "associations", definition: "has_many, belongs_to", study_set_id: study_set7.id})

Card.create({term: "quarterback", definition: "Passes or hands-off the ball to other players on the team in attempt to make completions and move down field to score. Usually is very athletic and has a good arm." , study_set_id: study_set8.id})
Card.create({term: "running back", definition: "player lined up behind the QB who rushes with the ball" , study_set_id: study_set8.id})
Card.create({term: "tight end", definition: "He lines up next to Offensive line men He blocks and catches the football", study_set_id: study_set8.id})
Card.create({term: "offensive lineman", definition: "a player that blocks, is not allowed to catch and plays at tackle, guard or center. Tackle and Guard have left and right positions", study_set_id: study_set8.id})
Card.create({term: "center", definition: "He hikes and blocks the ball", study_set_id: study_set8.id})
Card.create({term: "fullback", definition: "A running back that lines up behind the quarter back He blocks for the quarter back", study_set_id: study_set8.id})
Card.create({term: "wide receiver", definition: "The wide receiver lines up on the line of scrimmage towards the sidelines and runs patterns in ordr to get open for a pass", study_set_id: study_set8.id})
Card.create({term: "defensive tackle", definition: "The inner two members of the defensive line, whose jobs are to maintain their positions in order to stop a running play or to run through a gap in the offensive line to pressure the quarterback or disrupt the backfield formation.", study_set_id: study_set8.id})
Card.create({term: "defensive end", definition: "He faces the offensive tackle", study_set_id: study_set8.id})
Card.create({term: "linebackers", definition: "line up behind defensive lineman; defend the run, rush (QB), or cover (RB)/(WR)", study_set_id: study_set8.id})
Card.create({term: "cornerback", definition: "CB. They line up across from WR's and they mostly cover them to prevent complete passes, and try to intercept the ball. Occasionally they will rush the QB.", study_set_id: study_set8.id})
Card.create({term: "safeties", definition: "helps corner backs and prevents offense from scoring", study_set_id: study_set8.id})
Card.create({term: "sack", definition: "Defensive player tackles quarterback behind the line of scrimmage (behind the center player)", study_set_id: study_set8.id})
Card.create({term: "punt", definition: "A kick in which the ball is dropped and kicked before it reaches the ground. Used to give up the ball to the opposition after offensive downs have been used, as far down the field as possible.", study_set_id: study_set8.id})
Card.create({term: "kickoff", definition: "The way to start the game in the beginning and second half", study_set_id: study_set8.id})
Card.create({term: "interception", definition: "Defensive player catches quarterback pass", study_set_id: study_set8.id})
Card.create({term: "down", definition: "Any attempt to move the ball down the field", study_set_id: study_set8.id})
Card.create({term: "pass interference", definition: "When the ball is the air you can not touch any player trying to catch the ball ; 10 yard penalty (offensive)", study_set_id: study_set8.id})
Card.create({term: "offsides", definition: "Defensive player steps across the line of scrimmage before ball is hiked and makes contact with the offensive player", study_set_id: study_set8.id})
Card.create({term: "holding", definition: "Can not make contact with receivers 5 yard zone; 5 yard penalty and first down", study_set_id: study_set8.id})
Card.create({term: "spearing/facemask/holding", definition: "You can not tackle someone helmet first; 15 yard penalty", study_set_id: study_set8.id})
Card.create({term: "delay of game", definition: "Team has to start the play within a number of seconds; 5 yard penalty", study_set_id: study_set8.id})
Card.create({term: "line of scrimmage", definition: "an imaginary line across the width of the field that marks where a previous play just ended and a new play must start", study_set_id: study_set8.id})
Card.create({term: "neutral zone", definition: "An Imaginary area under the center that is hiking the ball", study_set_id: study_set8.id})

Card.create({term: "accio", definition: "A spell that summons something", study_set_id: study_set9.id})
Card.create({term: "expelliarmus", definition: "a charm that disarms your opponent", study_set_id: study_set9.id})
Card.create({term: "stupefy", definition: "a spell that stuns", study_set_id: study_set9.id})
Card.create({term: "avada kadavra", definition: "a spell that kills", study_set_id: study_set9.id})
Card.create({term: "flipendo", definition: "This spell can knock some one back", study_set_id: study_set9.id})

Card.create({term: "Mr.Toad", definition: "Mr.Toad's Wild Ride", study_set_id: study_set10.id})
Card.create({term: "Cinderella's Castle'", definition: "Walt Disney World", study_set_id: study_set10.id})
Card.create({term: "Sleeping Beauty's Castle", definition: "Disneyland", study_set_id: study_set10.id})
Card.create({term: "EPCOT", definition: "Walt Disney World Park", study_set_id: study_set10.id})
Card.create({term: "Main Street USA", definition: "both parks", study_set_id: study_set10.id})
Card.create({term: "Tower of Terror", definition: "both parks", study_set_id: study_set10.id})
Card.create({term: "The Matterhorn", definition: "Disneyland", study_set_id: study_set10.id})
Card.create({term: "Children of the World", definition: "It's A Small World After All", study_set_id: study_set10.id})

Card.create({term: "cupcake", definition: "Sweet cake-like but smaller", study_set_id: study_set11.id})
Card.create({term: "peppermint", definition: "Red white striped", study_set_id: study_set11.id})
Card.create({term: "twizzlers", definition: "Braided cherry flavored sweets", study_set_id: study_set11.id})
Card.create({term: "chocolate", definition: "Dark brown candy can be dark, milk or white", study_set_id: study_set11.id})
Card.create({term: "lemonhead", definition: "Lemon hard candy", study_set_id: study_set11.id})
Card.create({term: "caramel", definition: "light brown sticky stuff can cover apples", study_set_id: study_set11.id})
Card.create({term: "jelly beans", definition: "bean shaped different colors and flavors", study_set_id: study_set11.id})
Card.create({term: "jolly ranchers", definition: "hard candy different colors and flavors cylinder shapes", study_set_id: study_set11.id})

Card.create({term: "Americano", definition: "", study_set_id: study_set12.id})
Card.create({term: "Black eye", definition: "2 shots espresso, add to cup of brewed coffee", study_set_id: study_set12.id})
Card.create({term: "Breve", definition: "1 shot espresso, add small amount heated/steamed light cream or half & half", study_set_id: study_set12.id})
Card.create({term: "Cafe au Lait", definition: "Strong brewed coffee with steamed milk (no foam)", study_set_id: study_set12.id})
Card.create({term: "Caffe Latte", definition: "2 shots espresso, 3x as much steamed milk, top with foam", study_set_id: study_set12.id})
Card.create({term: "Cafe Mocha", definition: "2 shots espresso, 1 oz chocolate syrup, add steamed milk until full", study_set_id: study_set12.id})
Card.create({term: "Cappuccino", definition: "1/3 espresso, 1/3 steamed milk, 1/3 foam (or 1/2 espresso, 1/4 steamed milk, 1/4 foam)", study_set_id: study_set12.id})
Card.create({term: "Macchiato", definition: "1 shot espresso, 1 dollop foam", study_set_id: study_set12.id})
Card.create({term: "Mochaccino", definition: "1 shot espresso, 1 oz chocolate syrup, fill cup with stamed milk, top off with foam", study_set_id: study_set12.id})
Card.create({term: "Pulling an espresso shot", definition: "Compact/tamp grounds, typically 22 seconds,", study_set_id: study_set12.id})
Card.create({term: "Espresso shot", definition: "~ 1.5 oz", study_set_id: study_set12.id})
Card.create({term: "Shot in the Dark", definition: "1 shot espresso, add to brewed coffee", study_set_id: study_set12.id})

Card.create({term: "Rebound", definition: "Securing possession of the basketball after a missed shot", study_set_id: study_set13.id})
Card.create({term: "Zone", definition: "Separate or apportion into sections", study_set_id: study_set13.id})
Card.create({term: "Center", definition: "Position of a basketball player who participates in the jump", study_set_id: study_set13.id})
Card.create({term: "Assist", definition: "The act of enabling another player to make a good play", study_set_id: study_set13.id})
Card.create({term: "Court", definition: "A specially marked area within which a game is played", study_set_id: study_set13.id})
Card.create({term: "Foul", definition: "An act that violates the rules of a sport", study_set_id: study_set13.id})
Card.create({term: "Rim", definition: "The hoop from which the net is suspended", study_set_id: study_set13.id})
Card.create({term: "Upset", definition: "An improbable an unexpected victory", study_set_id: study_set13.id})
Card.create({term: "Dunk", definition: "A basketball shot in which the basketball is propelled downward into the basket", study_set_id: study_set13.id})
